---
title: "Acknowledgements"
author: "Whitlock and Schluter"

#output: html_document
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

The book and these websites are not the work of two people alone. We are fortunate to have had the help of a large number of people who have commented on chapters, reported errors, and made useful suggestions. In fact we have so many people to thank that we have run out of space in the printed book. In addition to the acknowledgments in the printed book, we would like to thank the following people who have helped us in many ways.

We have almost certainly forgotten someone who has been a help; there have been so many. If we've missed you here, please accept our thanks and apologies, and please write to remind us!

<br>

# Readers

The following people have generously read and commented on one or more chapters of the book, over the course of its three editions.Many of these good people read multiple chapters, and we thank all for their invaluable aid and considerate forebearance.

Anwar Ahmad, Arianne Albert, Sulekha Anand, Brad Anholt, Cécile Ané, Eric Baack, Mitchell Baker, Brandon Barton, Arthur Berg, Kelly Bodwin, Eline Boghaert, Yaniv Brandvain, Chad Brassil, James Bryant, Martin Buntinas, Mark Butler, Brett C. Byram, Chao Cai, Ashley J.R. Carter, Carrie Case, C. Ray Chandler, Laurel Chiappetta, Mark Clemens, Bradley Cosentino, Erika Crispo, Perry de Valpine, Flo Débarre, Tony Desmond, Eric Dewar, Abby Drake, Christiana Drake, Joseph E. Duchamp, Jonathan Dushoff, K M Flanagan, Matthias W. Foellmer, Demba Fofana, Steven George, Aleeza Gerstein, George Gilchrist, Brett Goodwin, Steven Green, B.E. Hagerty, Tim Hanson, R.N. Hartnett, Mike Hickerson, Lisa Hines, Eric S. Ho, Heather J. Hoffman, Dominique Ingato, Darren Irwin, Nusrat Jahan, Philip Johns, Roger Johnson, John Kalbfleisch, Istvan Karsai, Karry Kazial, Robert Keen, John Kelly, Rex Kenner, Ben Kerr, Yoon G. Kim, Jamie Kneitel, Laura Kubatko, Joseph G. Kunkel, Robert Laird, Bret Larget, Theo Light, Todd Livdahl, Heather J. Lynch, Rene Malenfant, Mike Marin, Heather Masonjones, Virginia Matzek, Brian C. McCarthy, Kevin Middleton, Eli Minkoff, Robert Montgomerie, Panagis Moschopoulos, Spencer Muse, Courtney Murren, Claudia Neuhauser, Liam O’Brien, Maria Orive, Sally Otto, Iain Pardoe, Elise Pasles, Patrick C. Phillips, Jay Pitocchelli, Danielle Presgraves, Nathan Rank, Bruce Rannala, Diann Reischman, Mark Rizzardi, James Robinson, Simon Robson, Michael Rosenberg, Noah Rosenberg, Anirudh V. S. Ruhil, Colin Rundel, Michael Russell, Ronald W. Russell, Paul Sajda, Andrew Schaffner, Andrea Schluter, Aimee Schwab-McCoy, James Scott, Ye Shen, Joel Shore, Andrew Skelton, John Soghigian, William Thomas, Andrew Tierman, Michael Travisano, Thomas Valone, Christopher Vitek, Bruce Walsh, Claus Wilke, David H. Wise, Michael Wunder, Grace A. Wyngaard, George Yanev, Sam Yeaman, and Amanda Zellmer. 

<br>

# Class testers

The following people have used a draft of the book in their classes and reported back with numerous useful comments.


Helen Alexander, Brad Anholt, Eric Baack, Carol Baskauf, Peter Dunn, Matthias Foellmer, Marie-Josée Fortin, George Gilchrist, Michael Grant, Joe Hardin, Karen Harper, Scott Harrison, Mike Hickerson, Stephen Hudman, Nusrat Jahan, Laura Kapitula, Randy Larsen, Terri Lacourse, Susan Lehman, Todd Livdahl, Kelly McCoy, Jean Richardson, Simon Robson, Chris Sanford, Tom Short, Andrew Tierman, Steve Vamosi, Liette Vasseur, Jason Wilson, and Grace A. Wyngaard

<br>

# Student and faculty readers

Many, many students and faculty in classes at UBC or from around the world have been generous enough to point out mistakes and other ways to improve the book over the years. The book has been greatly improved by these people:

Jessica Beaubier, Chad Brassil, Edward Cheung, Lorena Cheung, Stephanie Cheung, Denise Choi, Peter Dunn, Maryam Garabedian, Samrad Ghavimi, Inderjit Grewal, Rutger Hermsen, Sarah Hamanishi, Anne Harris, Yunhyung Ku, Gurpreet Khaira, Joanne Kim, Jung Min Kim, Arleigh Lambert, Alexander Leung, Mira Li, Flora Liu, Dianna Louie, Johnston Mak, Giovanni Marchetti, Luke Miller, Diana Moanga, Sarah Neumann, Jarad Niemi, Tyler Ng, Ruth Ogbamichael, Jasmine Ono, Chris Parrish, Jason Pither, Marion Pearson, Jessica Pham, Trevor Schofield, Melissa Smith, Meredith Soon, Erin Stacey, Daniel Stoebel, Myriam Tremblay, Michelle Uzelac, John Wakeley, Hillary Ward, Chris Wong, Irene Yu, Fei Yuan, Anush Zakaryan, Qiong Zhang, Paul Zhou, and Jon-Paul Zacharias.



