---
title: "Labs using R: <em>UBC Edition</em> <br>Getting R and RStudio"

output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
    includes:
      before_body: header_image.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*This lab is part of a series designed for BIOL 300, based on* The
Analysis of Biological Data*. The rest of the labs can be found
[here](index.html).*

------------------------------------------------------------------------

For these labs, you will need two apps on your computer: R and RStudio.
Both are free, available to download without charge from the
web. This setup requires a laptop or desktop computer; RStudio is not
natively supported on Chromebooks or iPads/tablets. Desktop computers
are available to use in 2004 Biological Sciences during BIOL 300
tutorial times (please consult your section's TA).

Advanced users are permitted to use VS Code or Positron, but note that
these apps are not fully endorsed by us. You may need to adapt
instructions and/or troubleshoot IDE-related problems on your own. See
the sections at the end of this page for more information about using VS
Code or Positron in BIOL 300.

<br>

# Step 1: Install R

A list of sites where R can be downloaded is maintained at
<https://cran.r-project.org/mirrors.html>. In most cases, the best
choice is [0-Cloud](https://cloud.r-project.org/). From the top box,
click on the link that matches your type of computer in the section
entitled "Download and Install R".

**Macs** -- If you have a Mac, you will likely first need to install
XQuartz from <https://www.xquartz.org>. After it downloads, click on the
`.dmg` file that appears in your downloads folder, and then form the
folder that opens, click on the `XQuartz.pkg` file. Follow the
installation instructions in the new window that opens.

To get R, choose the MacOS link from the CRAN website above. From the
resulting page (called “R for Mac OS X”) choose the `.pkg` file that
matches your version of the operating system – usually this is the first
one. Once the `.pkg` file has downloaded fully, open it and follow
instructions on screen.

**Windows** -- After choosing Windows from the CRAN page, click on the
first link for labeled “base”. Then click on the large top link
“Download R-X.Y.Z for Windows”. Run the `.exe` file that downloads.

<br>

# Step 2: Install RStudio

Go to [the download page for
RStudio](https://posit.co/download/rstudio-desktop). Assuming you
already installed R, look at the dropdown for "2: Install RStudio" and
choose an option that matches your operating system.

**Mac** – Open the `.dmg` file that downloads. In the resulting window,
drag & drop the RStudio icon into the Applications icon.

**Windows** – Run the `.exe` installer file that downloads.

<br>

# Step 3: Get ABDLabs

A `.zip` file for BIOL 300 that contains all the data sets, R scripts,
and some other features can be downloaded in a [folder called
ABDLabs](ABDLabs.zip). **After you download this `.zip` file, first
ensure that you move it outside of your computer's `Downloads` folder**.
Keeping this within the Downloads problem often causes permission errors
and other bugs. Most BIOL 300 students end up moving `ABDLabs.zip` to
the Desktop. After moving the `.zip` file, unzip it. It should then open
a folder called `ABDLabs`. Windows users: please be sure to fully unzip
the entire file and not just open the zip file, as this can cause
problems; the best practice is to right-click on it and choose "Extract
All" or a similar option.

Inside `ABDLabs` is one file and a couple folders. The folder `DataForLabs`
contains all the data sets that you will need to complete these labs;
any new data we create during the course should also be saved there. The
folder called `LearningTheTools` has an R script for each week,
containing all the commands described in that week’s instructions.
You’ll learn how to use these in Lab 1. The file `ABDLabs.Rproj` will
provide a way to open RStudio and ensure your working directory and
relative paths are set up on your computer; see further guidance below.

<br>

# Step 4: Start an RStudio session

There is a file in the `ABDLabs` folder called `ABDLabs.Rproj`. You can
double click on this file to start R and RStudio automatically. If you
start your session from this file, it will automatically set your
working directory in a way that aligns smoothly with our tutorials.
Opening `ABDLabs.Rproj` will automatically tell R to look inside the
`ABDLabs` folder for files like the data sets. Starting from this file
will make your life a little easier, and will also enforce a standard
environment for all submitted work.

<br>

# Support for VS Code or Positron

*These labs are designed around RStudio, but we permit usage of Visual
Studio Code (VS Code) or Positron for those who are already familiar
with these apps. If you are not familiar with ether VS Code or Positron,
use RStudio for these labs and don't worry about what is written below.*

The BIOL 300 instructional team only officially supports RStudio for our
labs. The tutorials, screenshots, and troubleshooting guidance
throughout the course assume that you are using RStudio. If you choose
to use VS Code or Positron instead, you may occasionally need to adapt
instructions and/or troubleshoot application-specific issues on your
own.

**Regardless of the app you choose, all submitted R scripts must be `.R`
file types and must follow BIOL 300 course conventions.** Your submitted
scripts must be able to reproduce results when run in a standard RStudio
environment. Course conventions include formatting expectations,
commenting practices, file naming, and script organization. Consult your
TA if you are uncertain about any of these.

BIOL 300 does not support the use of Jupyter notebooks. Although
advanced users may be able to configure Jupyter to work with R,
troubleshooting support for these setups will be limited. There is no 
dedicated Jupyter server for BIOL 300.

## Using R in VS Code

To use R in VS Code, you will first need to install the R extension for
VS Code. Within VS Code, open the Extensions panel and search for “R” by
Yuki Ueda (`REditorSupport.r`). Installing this extension provides
features such as syntax highlighting, code execution, plotting support,
and connections to the R console.

The `ABDLabs` folder distributed with these labs contains an `.Rproj`
file. This file is used by RStudio to define the project working
directory and session settings. VS Code does not directly use `.Rproj`
files, but you can still work with the labs successfully by opening the
entire `ABDLabs` folder in VS Code's Explorer or via
`File → Open Folder...`. Doing so helps ensure that relative file paths
used throughout the labs work correctly.

## Using R in Positron

Positron and RStudio are developed by the same company: Posit. Positron
combines features of RStudio and VS Code into a modern interface that
supports R, Python, Quarto, and other tools. Because Positron is still
under active development, some features may behave differently than they
do in RStudio.

The `.Rproj` file included in the `ABDLabs` folder is intended
for use with RStudio. Positron can still work with projects that contain
`.Rproj` files, but it does not rely on them in the same way that
RStudio does. As with VS Code, the best approach is to open the
`ABDLabs` folder in the Explorer or via `File → Open Folder...`. Doing
so helps ensure that relative file paths used throughout the labs work
correctly.
